import UIKit

/// Renders one challan from `ulip/echallan/01` as an A4 PDF.
///
/// Everything printed comes from the API response — there is no hardcoded state, department,
/// office or issuing-authority text anywhere in this file. A field the gateway didn't return
/// doesn't get a blank row, it gets no row at all, so a sparse challan produces a short clean
/// page instead of a form full of empty boxes. The only fixed strings are Itzeazy's own
/// branding and the provenance line in `footerNote`, which exists so the document can't be
/// mistaken for one an enforcement agency issued.
///
/// Drawn via the shared [PDFReportEngine] — colours and fonts still trace back to the literal
/// values ChallanDetailsView and ChallanDetailPopup use, but the page-flow machinery itself is
/// shared with the DL and Registration PDFs so all three stay visually identical.
enum ChallanPDFService {

    private typealias E = PDFReportEngine

    private static let footerNote =
        "Generated by Itzeazy from ULIP (Government of India) records. Not an enforcement " +
        "notice. Names and licence numbers are masked at source."

    // MARK: - Entry point

    static func generate(challan: ULIPChallanEntry, vehicle: ChallanPDFVehicleContext?) -> Data {
        let bounds = CGRect(x: 0, y: 0, width: E.pageWidth, height: E.pageHeight)

        // First pass draws a real (but discarded) document purely to learn the true page
        // count, so the second pass can print a truthful "Page 1 of 2" in the footer. Each
        // pass gets its OWN renderer — calling pdfData(actions:) twice on the same
        // UIGraphicsPDFRenderer instance is unreliable in practice and can come back with
        // empty Data on the second call, so this never reuses one across passes.
        var pageCount = 1
        _ = UIGraphicsPDFRenderer(bounds: bounds).pdfData { rendererContext in
            let flow = E.PageFlow(context: rendererContext, bounds: bounds, totalPages: 0, footerNote: footerNote)
            draw(flow: flow, challan: challan, vehicle: vehicle)
            flow.finishPage()
            pageCount = flow.pageCount
        }

        return UIGraphicsPDFRenderer(bounds: bounds).pdfData { rendererContext in
            let flow = E.PageFlow(context: rendererContext, bounds: bounds, totalPages: pageCount, footerNote: footerNote)
            draw(flow: flow, challan: challan, vehicle: vehicle)
            flow.finishPage()
        }
    }

    // MARK: - Layout

    private static func draw(flow: E.PageFlow, challan c: ULIPChallanEntry, vehicle v: ChallanPDFVehicleContext?) {
        flow.startPage()
        header(flow, c)
        challanIdentity(flow, c)
        amounts(flow, c)

        flow.section("Challan Details")
        flow.grid([
            ("Challan Date & Time", ChallanMapper.cleaned(c.challan_date_time)),
            ("Status", ChallanMapper.cleaned(c.challan_status)),
            ("Department", ChallanMapper.cleaned(c.department)),
            ("State Code", ChallanMapper.cleaned(c.state_code)),
            ("RTO District", ChallanMapper.cleaned(c.rto_distric_name)),
            ("Sent to Court", ChallanMapper.cleaned(c.sent_to_reg_court)),
            ("Sent to Virtual Court", ChallanMapper.cleaned(c.sent_to_virtual_court)),
            ("Sent to Court On", ChallanMapper.cleaned(c.sent_to_court_on)),
            ("Date of Proceeding", ChallanMapper.cleaned(c.date_of_proceeding)),
            ("Receipt No.", ChallanMapper.cleaned(c.receipt_no)),
            ("Received Amount", c.received_amount.map { E.rupees($0) }),
            ("Document Impounded", ChallanMapper.cleaned(c.document_impounded))
        ])
        flow.wideRow(label: "Place of Offence", value: ChallanMapper.cleaned(c.challan_place))

        var vehicleRows: [(String, String)] = []
        if let vehicleNo = v?.vehicleNumber.flatMap(ChallanMapper.cleaned) { vehicleRows.append(("Vehicle No.", vehicleNo)) }
        if let vClass = v?.vehicleClass.flatMap(ChallanMapper.cleaned) { vehicleRows.append(("Vehicle Class", vClass)) }
        if let model = v?.model.flatMap(ChallanMapper.cleaned) { vehicleRows.append(("Maker / Model", model)) }
        if let rto = v?.rto.flatMap(ChallanMapper.cleaned) { vehicleRows.append(("Registered At", rto)) }
        if let chassis = v?.chassisNo.flatMap(ChallanMapper.cleaned) { vehicleRows.append(("Chassis No.", chassis)) }
        if let engine = v?.engineNo.flatMap(ChallanMapper.cleaned) { vehicleRows.append(("Engine No.", engine)) }

        var people: [(String, String)] = []
        if let owner = (v?.ownerName.flatMap(ChallanMapper.cleaned)) ?? ChallanMapper.cleaned(c.owner_name) {
            people.append(("Owner's Name", owner))
        }
        if let violator = ChallanMapper.cleaned(c.name_of_violator) { people.append(("Violator", violator)) }
        if let driver = ChallanMapper.cleaned(c.driver_name) { people.append(("Driver's Name", driver)) }
        if let dl = ChallanMapper.cleaned(c.dl_no) { people.append(("DL No.", dl)) }

        if !vehicleRows.isEmpty || !people.isEmpty {
            flow.section("Vehicle & Owner")
            flow.grid((vehicleRows + people).map { ($0.0, $0.1 as String?) })
        }

        let offences = (c.offence_details ?? []).filter {
            ChallanMapper.cleaned($0.name) != nil || ChallanMapper.cleaned($0.act) != nil
        }
        if !offences.isEmpty {
            flow.section("Offence Details")
            flow.table(
                offences.map {
                    (ChallanMapper.cleaned($0.name) ?? "—", ChallanMapper.cleaned($0.act) ?? "—", $0.offence_id.map(String.init) ?? "—")
                },
                headers: ("OFFENCE", "ACT", "CODE")
            )
        }

        let court = [ChallanMapper.cleaned(c.court_name), ChallanMapper.cleaned(c.court_address)].compactMap { $0 }
        if !court.isEmpty {
            flow.section("Court")
            flow.wideRow(label: "Court", value: court.joined(separator: "\n"))
        }

        if let remark = ChallanMapper.cleaned(c.remark) {
            flow.section("Remarks")
            flow.paragraph(remark)
        }
    }

    private static func header(_ flow: E.PageFlow, _ c: ULIPChallanEntry) {
        let dept = ChallanMapper.cleaned(c.department)
        let state = ChallanMapper.cleaned(c.state_code)
        let title = [dept, state.map { "(\($0))" }]
            .compactMap { $0 }
            .joined(separator: " ")
        let displayTitle = title.isEmpty ? "Traffic Challan" : title

        flow.header(logo: UIImage(named: "itzeazy_logo"), title: displayTitle, subtitle: ChallanMapper.cleaned(c.rto_distric_name))
    }

    private static func challanIdentity(_ flow: E.PageFlow, _ c: ULIPChallanEntry) {
        let status = ChallanMapper.cleaned(c.challan_status)
        let isPending = status?.lowercased() == "pending"
        flow.identityBlock(
            label: "CHALLAN NO",
            value: ChallanMapper.cleaned(c.challan_no) ?? "—",
            statusText: status,
            statusBackground: isPending ? E.Palette.pendingBg : E.Palette.closedBg,
            statusForeground: isPending ? E.Palette.pendingFg : E.Palette.closedFg
        )
    }

    /// `fine_imposed` (the statutory fine) and `amount_of_fine_imposed` (what a court settled
    /// on) are different quantities and only the first is always returned, so each is printed
    /// under its own label and only when present — never merged into one invented total.
    private static func amounts(_ flow: E.PageFlow, _ c: ULIPChallanEntry) {
        let imposed = c.fine_imposed.flatMap { Int($0) }
        let payable = c.amount_of_fine_imposed.flatMap { Double($0) }.map { Int($0) }
        guard imposed != nil || payable != nil else { return }

        let boxHeight: CGFloat = 62
        let box = CGRect(x: E.margin, y: flow.y, width: E.pageWidth - E.margin * 2, height: boxHeight)
        flow.round(box, radius: 12, color: E.Palette.surface)
        flow.fill(CGRect(x: E.margin, y: flow.y, width: 4, height: boxHeight), color: E.Palette.red)

        var x = E.margin + 20
        let entries: [(String, String)] = [
            imposed.map { ("FINE IMPOSED", E.rupees($0)) },
            payable.map { ("AMOUNT PAYABLE", E.rupees($0)) }
        ].compactMap { $0 }
        for (label, value) in entries {
            flow.text(label, topLeft: CGPoint(x: x, y: flow.y + 12), font: E.Fonts.label, color: E.Palette.muted)
            flow.text(value, topLeft: CGPoint(x: x, y: flow.y + 28), font: E.Fonts.amount, color: E.Palette.red)
            x += 168
        }
        flow.y += boxHeight + 22
    }
}
