import UIKit

/// Renders one challan from `ulip/echallan/01` as an A4 PDF.
///
/// Everything printed comes from the API response — there is no hardcoded state, department,
/// office or issuing-authority text anywhere in this file. A field the gateway didn't return
/// doesn't get a blank row, it gets no row at all, so a sparse challan produces a short clean
/// page instead of a form full of empty boxes. The only fixed strings are Itzeazy's own
/// branding and the provenance line in `footerNote`, which exists so the document can't be
/// mistaken for one an enforcement agency issued.
///
/// Colours and fonts are pulled straight from the literal values ChallanDetailsView and
/// ChallanDetailPopup already use (ink `(0.10, 0.11, 0.11)`, red `(0.93, 0.13, 0.14)`, the
/// pending-pill pair, PlusJakartaSans for headings) rather than a separate palette, so the
/// PDF reads as the same app rather than a re-skinned one. "Inter" — used in SwiftUI via
/// `Font.custom("Inter", …)` throughout those screens — isn't declared in Info.plist's
/// UIAppFonts, so it silently falls back to the system font there already; body text here
/// uses the system font for the same reason, matching what actually renders on screen rather
/// than what the SwiftUI code names.
enum ChallanPDFService {

    // A4 in points, the unit UIGraphicsPDFRenderer draws in.
    private static let pageWidth: CGFloat = 595
    private static let pageHeight: CGFloat = 842
    private static let margin: CGFloat = 36
    private static let colGap: CGFloat = 20
    private static let footerHeight: CGFloat = 50

    private enum Palette {
        static let ink = UIColor(red: 0.10, green: 0.11, blue: 0.11, alpha: 1)
        static let red = UIColor(red: 0.93, green: 0.13, blue: 0.14, alpha: 1)
        static let muted = UIColor(red: 0.52, green: 0.52, blue: 0.52, alpha: 1)
        static let line = UIColor(white: 0.85, alpha: 1)
        static let surface = UIColor(white: 0.97, alpha: 1)
        static let pendingBg = UIColor(red: 1.00, green: 0.85, blue: 0.84, alpha: 1)
        static let pendingFg = UIColor(red: 0.58, green: 0.00, blue: 0.04, alpha: 1)
        static let closedBg = UIColor(white: 0.90, alpha: 1)
        static let closedFg = UIColor(white: 0.40, alpha: 1)
    }

    private static func jakarta(_ weight: String, _ size: CGFloat) -> UIFont {
        UIFont(name: "PlusJakartaSans-\(weight)", size: size) ?? .boldSystemFont(ofSize: size)
    }

    private static let titleFont = jakarta("ExtraBold", 15)
    private static let hugeFont = jakarta("ExtraBold", 19)
    private static let sectionFont = jakarta("Bold", 9.5)
    private static let amountFont = jakarta("Bold", 17)
    private static let statusFont = jakarta("Bold", 8)
    private static let labelFont = UIFont.systemFont(ofSize: 7.5, weight: .semibold)
    private static let valueFont = UIFont.systemFont(ofSize: 10, weight: .medium)
    private static let mutedFont = UIFont.systemFont(ofSize: 9.5, weight: .regular)
    private static let subFont = UIFont.systemFont(ofSize: 8.5, weight: .regular)
    private static let footerFont = UIFont.systemFont(ofSize: 7, weight: .regular)

    private static let footerNote =
        "Generated by Itzeazy from ULIP (Government of India) records. Not an enforcement " +
        "notice. Names and licence numbers are masked at source."

    private static let generatedFormatter: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "d MMM yyyy, h:mm a"
        return f
    }()

    private static let amountFormatter: NumberFormatter = {
        let f = NumberFormatter()
        f.numberStyle = .decimal
        f.locale = Locale.current
        return f
    }()

    private static func rupees(_ value: Int) -> String {
        "₹ " + (amountFormatter.string(from: NSNumber(value: value)) ?? "\(value)")
    }

    // MARK: - Entry point

    static func generate(challan: ULIPChallanEntry, vehicle: ChallanPDFVehicleContext?) -> Data {
        let bounds = CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight)

        // First pass draws a real (but discarded) document purely to learn the true page
        // count, so the second pass can print a truthful "Page 1 of 2" in the footer. Each
        // pass gets its OWN renderer — calling pdfData(actions:) twice on the same
        // UIGraphicsPDFRenderer instance is unreliable in practice and can come back with
        // empty Data on the second call, so this never reuses one across passes.
        var pageCount = 1
        _ = UIGraphicsPDFRenderer(bounds: bounds).pdfData { rendererContext in
            let flow = PageFlow(context: rendererContext, bounds: bounds, totalPages: 0)
            draw(flow: flow, challan: challan, vehicle: vehicle)
            flow.finishPage()
            pageCount = flow.pageCount
        }

        return UIGraphicsPDFRenderer(bounds: bounds).pdfData { rendererContext in
            let flow = PageFlow(context: rendererContext, bounds: bounds, totalPages: pageCount)
            draw(flow: flow, challan: challan, vehicle: vehicle)
            flow.finishPage()
        }
    }

    // MARK: - Layout

    private static func draw(flow: PageFlow, challan c: ULIPChallanEntry, vehicle v: ChallanPDFVehicleContext?) {
        flow.startPage()
        header(flow, c)
        challanIdentity(flow, c)
        amounts(flow, c)

        flow.section("Challan Details")
        flow.grid([
            ("Challan Date & Time", ChallanMapper.cleaned(c.challan_date_time)),
            ("Status", ChallanMapper.cleaned(c.challan_status)),
            ("Department", ChallanMapper.cleaned(c.department)),
            ("State Code", ChallanMapper.cleaned(c.state_code)),
            ("RTO District", ChallanMapper.cleaned(c.rto_distric_name)),
            ("Sent to Court", ChallanMapper.cleaned(c.sent_to_reg_court)),
            ("Sent to Virtual Court", ChallanMapper.cleaned(c.sent_to_virtual_court)),
            ("Sent to Court On", ChallanMapper.cleaned(c.sent_to_court_on)),
            ("Date of Proceeding", ChallanMapper.cleaned(c.date_of_proceeding)),
            ("Receipt No.", ChallanMapper.cleaned(c.receipt_no)),
            ("Received Amount", c.received_amount.map { rupees($0) }),
            ("Document Impounded", ChallanMapper.cleaned(c.document_impounded))
        ])
        flow.wideRow(label: "Place of Offence", value: ChallanMapper.cleaned(c.challan_place))

        var vehicleRows: [(String, String)] = []
        if let vehicleNo = v?.vehicleNumber.flatMap(ChallanMapper.cleaned) { vehicleRows.append(("Vehicle No.", vehicleNo)) }
        if let vClass = v?.vehicleClass.flatMap(ChallanMapper.cleaned) { vehicleRows.append(("Vehicle Class", vClass)) }
        if let model = v?.model.flatMap(ChallanMapper.cleaned) { vehicleRows.append(("Maker / Model", model)) }
        if let rto = v?.rto.flatMap(ChallanMapper.cleaned) { vehicleRows.append(("Registered At", rto)) }
        if let chassis = v?.chassisNo.flatMap(ChallanMapper.cleaned) { vehicleRows.append(("Chassis No.", chassis)) }
        if let engine = v?.engineNo.flatMap(ChallanMapper.cleaned) { vehicleRows.append(("Engine No.", engine)) }

        var people: [(String, String)] = []
        if let owner = (v?.ownerName.flatMap(ChallanMapper.cleaned)) ?? ChallanMapper.cleaned(c.owner_name) {
            people.append(("Owner's Name", owner))
        }
        if let violator = ChallanMapper.cleaned(c.name_of_violator) { people.append(("Violator", violator)) }
        if let driver = ChallanMapper.cleaned(c.driver_name) { people.append(("Driver's Name", driver)) }
        if let dl = ChallanMapper.cleaned(c.dl_no) { people.append(("DL No.", dl)) }

        if !vehicleRows.isEmpty || !people.isEmpty {
            flow.section("Vehicle & Owner")
            flow.grid((vehicleRows + people).map { ($0.0, $0.1 as String?) })
        }

        let offences = (c.offence_details ?? []).filter {
            ChallanMapper.cleaned($0.name) != nil || ChallanMapper.cleaned($0.act) != nil
        }
        if !offences.isEmpty {
            flow.section("Offence Details")
            flow.offenceTable(offences.map {
                (ChallanMapper.cleaned($0.name) ?? "—", ChallanMapper.cleaned($0.act) ?? "—", $0.offence_id.map(String.init) ?? "—")
            })
        }

        let court = [ChallanMapper.cleaned(c.court_name), ChallanMapper.cleaned(c.court_address)].compactMap { $0 }
        if !court.isEmpty {
            flow.section("Court")
            flow.wideRow(label: "Court", value: court.joined(separator: "\n"))
        }

        if let remark = ChallanMapper.cleaned(c.remark) {
            flow.section("Remarks")
            flow.paragraph(remark)
        }
    }

    private static func header(_ flow: PageFlow, _ c: ULIPChallanEntry) {
        let bandHeight: CGFloat = 104
        flow.fill(CGRect(x: 0, y: 0, width: pageWidth, height: bandHeight), color: Palette.ink)
        flow.fill(CGRect(x: 0, y: bandHeight, width: pageWidth, height: 4), color: Palette.red)

        if let logo = UIImage(named: "itzeazy_logo") {
            let width: CGFloat = 104
            let height = logo.size.height * (width / logo.size.width)
            flow.image(logo, rect: CGRect(x: margin, y: 26, width: width, height: height))
        }

        let dept = ChallanMapper.cleaned(c.department)
        let state = ChallanMapper.cleaned(c.state_code)
        let title = [dept, state.map { "(\($0))" }]
            .compactMap { $0 }
            .joined(separator: " ")
        let displayTitle = (title.isEmpty ? "Traffic Challan" : title).uppercased()

        flow.text(displayTitle, topRight: CGPoint(x: pageWidth - margin, y: 22), font: titleFont, color: .white)
        var subY: CGFloat = 44
        if let rto = ChallanMapper.cleaned(c.rto_distric_name) {
            flow.text(rto, topRight: CGPoint(x: pageWidth - margin, y: subY), font: subFont, color: UIColor(white: 0.65, alpha: 1))
            subY += 14
        }
        flow.text(
            "Generated \(generatedFormatter.string(from: Date()))",
            topRight: CGPoint(x: pageWidth - margin, y: subY),
            font: subFont, color: UIColor(white: 0.65, alpha: 1)
        )

        flow.y = bandHeight + 4 + 22
    }

    private static func challanIdentity(_ flow: PageFlow, _ c: ULIPChallanEntry) {
        flow.text("CHALLAN NO", topLeft: CGPoint(x: margin, y: flow.y), font: labelFont, color: Palette.muted)
        flow.y += 14
        let no = ChallanMapper.cleaned(c.challan_no) ?? "—"
        flow.text(no, topLeft: CGPoint(x: margin, y: flow.y), font: hugeFont, color: Palette.ink)

        if let status = ChallanMapper.cleaned(c.challan_status) {
            let isPending = status.lowercased() == "pending"
            let bg = isPending ? Palette.pendingBg : Palette.closedBg
            let fg = isPending ? Palette.pendingFg : Palette.closedFg
            let label = status.uppercased()
            let textSize = (label as NSString).size(withAttributes: [.font: statusFont])
            let pillWidth = textSize.width + 24
            let pillRect = CGRect(x: pageWidth - margin - pillWidth, y: flow.y - 2, width: pillWidth, height: 20)
            flow.round(pillRect, radius: 9, color: bg)
            flow.text(label, center: CGPoint(x: pillRect.midX, y: pillRect.midY), font: statusFont, color: fg)
        }
        flow.y += 30
    }

    /// `fine_imposed` (the statutory fine) and `amount_of_fine_imposed` (what a court settled
    /// on) are different quantities and only the first is always returned, so each is printed
    /// under its own label and only when present — never merged into one invented total.
    private static func amounts(_ flow: PageFlow, _ c: ULIPChallanEntry) {
        let imposed = c.fine_imposed.flatMap { Int($0) }
        let payable = c.amount_of_fine_imposed.flatMap { Double($0) }.map { Int($0) }
        guard imposed != nil || payable != nil else { return }

        let boxHeight: CGFloat = 62
        let box = CGRect(x: margin, y: flow.y, width: pageWidth - margin * 2, height: boxHeight)
        flow.round(box, radius: 12, color: Palette.surface)
        flow.fill(CGRect(x: margin, y: flow.y, width: 4, height: boxHeight), color: Palette.red)

        var x = margin + 20
        let entries: [(String, String)] = [
            imposed.map { ("FINE IMPOSED", rupees($0)) },
            payable.map { ("AMOUNT PAYABLE", rupees($0)) }
        ].compactMap { $0 }
        for (label, value) in entries {
            flow.text(label, topLeft: CGPoint(x: x, y: flow.y + 12), font: labelFont, color: Palette.muted)
            flow.text(value, topLeft: CGPoint(x: x, y: flow.y + 28), font: amountFont, color: Palette.red)
            x += 168
        }
        flow.y += boxHeight + 22
    }

    // MARK: - Page flow

    /// Cursor over the document, mirroring the layout primitives used throughout: fixed A4
    /// bounds, a running `y`, and page breaks that redraw the footer before starting fresh.
    private final class PageFlow {
        private let context: UIGraphicsPDFRendererContext
        private let bounds: CGRect
        private let totalPages: Int
        private(set) var pageCount = 0
        var y: CGFloat = margin

        init(context: UIGraphicsPDFRendererContext, bounds: CGRect, totalPages: Int) {
            self.context = context
            self.bounds = bounds
            self.totalPages = totalPages
        }

        func startPage() {
            pageCount += 1
            // The explicit-bounds overload, matching DocumentScannerPDFService's own proven
            // pattern elsewhere in this app — the bare beginPage() relies on the renderer
            // picking up its format bounds implicitly, which produced an empty (0-byte) PDF.
            context.beginPage(withBounds: bounds, pageInfo: [:])
            y = margin
        }

        /// Draws the footer on the still-open current page, then advances to a new one.
        /// Calling `beginPage()` again implicitly closes whatever page is currently open, so
        /// the footer must be drawn before that call, not after.
        func finishPage() {
            drawFooter()
        }

        private func breakPageIfNeeded(_ needed: CGFloat) {
            guard y + needed > pageHeight - footerHeight else { return }
            finishPage()
            startPage()
        }

        private func drawFooter() {
            let top = pageHeight - footerHeight
            let cg = context.cgContext
            cg.setStrokeColor(Palette.line.cgColor)
            cg.setLineWidth(0.8)
            cg.move(to: CGPoint(x: margin, y: top))
            cg.addLine(to: CGPoint(x: pageWidth - margin, y: top))
            cg.strokePath()

            let noteWidth = pageWidth - margin * 2 - 70
            drawBlock(footerNote, font: footerFont, color: Palette.muted,
                      rect: CGRect(x: margin, y: top + 10, width: noteWidth, height: footerHeight - 14))

            let label = totalPages > 0 ? "Page \(pageCount) of \(totalPages)" : "Page \(pageCount)"
            text(label, topRight: CGPoint(x: pageWidth - margin, y: top + 12), font: footerFont, color: Palette.muted)
        }

        // MARK: Drawing primitives

        func fill(_ rect: CGRect, color: UIColor) {
            color.setFill()
            UIRectFill(rect)
        }

        func round(_ rect: CGRect, radius: CGFloat, color: UIColor) {
            let path = UIBezierPath(roundedRect: rect, cornerRadius: radius)
            color.setFill()
            path.fill()
        }

        func image(_ image: UIImage, rect: CGRect) {
            image.draw(in: rect)
        }

        func text(_ s: String, topLeft: CGPoint, font: UIFont, color: UIColor) {
            (s as NSString).draw(at: topLeft, withAttributes: [.font: font, .foregroundColor: color])
        }

        func text(_ s: String, topRight: CGPoint, font: UIFont, color: UIColor) {
            let width = (s as NSString).size(withAttributes: [.font: font]).width
            text(s, topLeft: CGPoint(x: topRight.x - width, y: topRight.y), font: font, color: color)
        }

        func text(_ s: String, center: CGPoint, font: UIFont, color: UIColor) {
            let size = (s as NSString).size(withAttributes: [.font: font])
            text(s, topLeft: CGPoint(x: center.x - size.width / 2, y: center.y - size.height / 2), font: font, color: color)
        }

        /// Height a wrapped block of [text] would need at [width], without drawing it.
        func measuredHeight(_ text: String, font: UIFont, width: CGFloat) -> CGFloat {
            let bounds = (text as NSString).boundingRect(
                with: CGSize(width: width, height: .greatestFiniteMagnitude),
                options: [.usesLineFragmentOrigin, .usesFontLeading],
                attributes: [.font: font], context: nil
            )
            return ceil(bounds.height)
        }

        func drawBlock(_ text: String, font: UIFont, color: UIColor, rect: CGRect) {
            let paragraph = NSMutableParagraphStyle()
            paragraph.lineBreakMode = .byWordWrapping
            (text as NSString).draw(
                with: rect,
                options: [.usesLineFragmentOrigin, .usesFontLeading],
                attributes: [.font: font, .foregroundColor: color, .paragraphStyle: paragraph],
                context: nil
            )
        }

        // MARK: Layout blocks

        func section(_ title: String) {
            breakPageIfNeeded(46)
            y += 8
            text(title.uppercased(), topLeft: CGPoint(x: margin, y: y), font: sectionFont, color: Palette.red)
            y += 18
            let cg = context.cgContext
            cg.setStrokeColor(Palette.line.cgColor)
            cg.setLineWidth(0.8)
            cg.move(to: CGPoint(x: margin, y: y))
            cg.addLine(to: CGPoint(x: pageWidth - margin, y: y))
            cg.strokePath()
            y += 14
        }

        /// Two-column label/value grid. Rows whose value is nil are dropped, not rendered blank.
        func grid(_ rows: [(String, String?)]) {
            let present = rows.compactMap { row -> (String, String)? in
                guard let value = row.1 else { return nil }
                return (row.0, value)
            }
            let colWidth = (pageWidth - margin * 2 - colGap) / 2
            var index = 0
            while index < present.count {
                let pair = Array(present[index..<min(index + 2, present.count)])
                let heights = pair.map { measuredHeight($0.1, font: valueFont, width: colWidth) }
                let rowHeight = heights.max() ?? 0
                breakPageIfNeeded(rowHeight + 20)
                let rowTop = y
                for (i, (label, value)) in pair.enumerated() {
                    let x = margin + CGFloat(i) * (colWidth + colGap)
                    text(label.uppercased(), topLeft: CGPoint(x: x, y: rowTop), font: labelFont, color: Palette.muted)
                    drawBlock(value, font: valueFont, color: Palette.ink,
                              rect: CGRect(x: x, y: rowTop + 12, width: colWidth, height: rowHeight + 4))
                }
                y = rowTop + 12 + rowHeight + 12
                index += 2
            }
        }

        /// Full-width label/value, for long text that would be cramped in a grid column.
        func wideRow(label: String, value: String?) {
            guard let value else { return }
            let width = pageWidth - margin * 2
            let height = measuredHeight(value, font: valueFont, width: width)
            breakPageIfNeeded(height + 24)
            text(label.uppercased(), topLeft: CGPoint(x: margin, y: y), font: labelFont, color: Palette.muted)
            y += 12
            drawBlock(value, font: valueFont, color: Palette.ink, rect: CGRect(x: margin, y: y, width: width, height: height + 4))
            y += height + 12
        }

        func paragraph(_ text: String) {
            let width = pageWidth - margin * 2
            let height = measuredHeight(text, font: valueFont, width: width)
            breakPageIfNeeded(height + 8)
            drawBlock(text, font: valueFont, color: Palette.ink, rect: CGRect(x: margin, y: y, width: width, height: height + 4))
            y += height + 8
        }

        /// Every offence on the challan, not just the first. No per-offence amount column:
        /// the gateway returns one fine for the whole challan, so a per-row figure would be
        /// the same number repeated and would read as if it were charged more than once.
        func offenceTable(_ rows: [(String, String, String)]) {
            let actWidth: CGFloat = 84
            let idWidth: CGFloat = 64
            let nameWidth = pageWidth - margin * 2 - actWidth - idWidth - colGap * 2

            breakPageIfNeeded(30)
            text("OFFENCE", topLeft: CGPoint(x: margin, y: y), font: labelFont, color: Palette.muted)
            text("ACT", topLeft: CGPoint(x: margin + nameWidth + colGap, y: y), font: labelFont, color: Palette.muted)
            text("CODE", topLeft: CGPoint(x: margin + nameWidth + actWidth + colGap * 2, y: y), font: labelFont, color: Palette.muted)
            y += 14
            let cg = context.cgContext
            cg.setStrokeColor(Palette.line.cgColor)
            cg.setLineWidth(0.8)
            cg.move(to: CGPoint(x: margin, y: y))
            cg.addLine(to: CGPoint(x: pageWidth - margin, y: y))
            cg.strokePath()
            y += 10

            for (index, row) in rows.enumerated() {
                let (name, act, code) = row
                let height = measuredHeight(name, font: valueFont, width: nameWidth)
                breakPageIfNeeded(height + 16)
                let top = y
                if index % 2 == 1 {
                    round(CGRect(x: margin - 6, y: top - 6, width: pageWidth - margin * 2 + 12, height: height + 16), radius: 6, color: Palette.surface)
                }
                drawBlock(name, font: valueFont, color: Palette.ink, rect: CGRect(x: margin, y: top, width: nameWidth, height: height + 4))
                text(act, topLeft: CGPoint(x: margin + nameWidth + colGap, y: top), font: valueFont, color: Palette.ink)
                text(code, topLeft: CGPoint(x: margin + nameWidth + actWidth + colGap * 2, y: top), font: mutedFont, color: Palette.muted)
                y = top + height + 14
            }
        }
    }
}
