import UIKit

/// Shared A4 report engine behind every PDF Itzeazy generates on iOS (challans, driving
/// licences, registration certificates). Centralising the page-flow, palette and typography
/// here keeps every generated document visually identical instead of several near-duplicate
/// copies of the same layout code.
enum PDFReportEngine {

    // A4 in points, the unit UIGraphicsPDFRenderer draws in.
    static let pageWidth: CGFloat = 595
    static let pageHeight: CGFloat = 842
    static let margin: CGFloat = 36
    static let colGap: CGFloat = 20
    static let footerHeight: CGFloat = 50

    /// Colours pulled from the literal values already used on-screen (ChallanDetailsView /
    /// ChallanDetailPopup / DLInfoView / RegistrationDetailsView), not a separate palette, so
    /// each PDF reads as the same screen rather than a re-skinned document.
    enum Palette {
        static let ink = UIColor(red: 0.10, green: 0.11, blue: 0.11, alpha: 1)
        static let red = UIColor(red: 0.93, green: 0.13, blue: 0.14, alpha: 1)
        static let muted = UIColor(red: 0.52, green: 0.52, blue: 0.52, alpha: 1)
        static let line = UIColor(white: 0.85, alpha: 1)
        static let surface = UIColor(white: 0.97, alpha: 1)

        // Challan status pill — pending (red) vs closed (gray), matching ChallanDetailPopup's
        // own "disposed" convention, not a green/red pair.
        static let pendingBg = UIColor(red: 1.00, green: 0.85, blue: 0.84, alpha: 1)
        static let pendingFg = UIColor(red: 0.58, green: 0.00, blue: 0.04, alpha: 1)
        static let closedBg = UIColor(white: 0.90, alpha: 1)
        static let closedFg = UIColor(white: 0.40, alpha: 1)

        // DL Info's "Current Status" pill — solid green fill with white text, matching
        // DLBasicInfoSection in DLInfoView.swift exactly.
        static let dlStatusBg = UIColor(red: 0.18, green: 0.72, blue: 0.42, alpha: 1)
        static let dlStatusFg = UIColor.white

        // Registration's status pill — light green tint with green text, matching
        // RegistrationDetailsView in VehicleComponents.swift exactly.
        static let rcStatusBg = UIColor.systemGreen.withAlphaComponent(0.2)
        static let rcStatusFg = UIColor.systemGreen

        // TS DL's status dot — green when ACTIVE, orange otherwise, matching
        // TSDLHeaderCard's own dot+label convention. The one status pill in the app that's
        // genuinely conditional on the value rather than effectively always one color.
        static let tsdlActiveBg = UIColor.systemGreen.withAlphaComponent(0.15)
        static let tsdlActiveFg = UIColor.systemGreen
        static let tsdlInactiveBg = UIColor.systemOrange.withAlphaComponent(0.15)
        static let tsdlInactiveFg = UIColor.systemOrange
    }

    static func jakarta(_ weight: String, _ size: CGFloat) -> UIFont {
        UIFont(name: "PlusJakartaSans-\(weight)", size: size) ?? .boldSystemFont(ofSize: size)
    }

    enum Fonts {
        static let title = PDFReportEngine.jakarta("ExtraBold", 15)
        static let huge = PDFReportEngine.jakarta("ExtraBold", 19)
        static let section = PDFReportEngine.jakarta("Bold", 9.5)
        static let amount = PDFReportEngine.jakarta("Bold", 17)
        static let status = PDFReportEngine.jakarta("Bold", 8)
        static let label = UIFont.systemFont(ofSize: 7.5, weight: .semibold)
        static let value = UIFont.systemFont(ofSize: 10, weight: .medium)
        static let muted = UIFont.systemFont(ofSize: 9.5, weight: .regular)
        static let sub = UIFont.systemFont(ofSize: 8.5, weight: .regular)
        static let footer = UIFont.systemFont(ofSize: 7, weight: .regular)
    }

    /// Default provenance line. Challan overrides this with its own enforcement-specific
    /// wording; DL and Registration use this generic one as-is.
    static let defaultFooterNote =
        "Generated by Itzeazy from ULIP (Government of India) records. For reference only — " +
        "not an official government-issued document."

    private static let generatedFormatter: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "d MMM yyyy, h:mm a"
        return f
    }()

    private static let amountFormatter: NumberFormatter = {
        let f = NumberFormatter()
        f.numberStyle = .decimal
        f.locale = Locale.current
        return f
    }()

    static func rupees(_ value: Int) -> String {
        "₹ " + (amountFormatter.string(from: NSNumber(value: value)) ?? "\(value)")
    }

    // MARK: - Page flow

    /// Cursor over the document: fixed A4 bounds, a running `y`, and page breaks that redraw
    /// the footer before starting fresh.
    final class PageFlow {
        private let context: UIGraphicsPDFRendererContext
        private let bounds: CGRect
        private let totalPages: Int
        private let footerNote: String
        private(set) var pageCount = 0
        var y: CGFloat = PDFReportEngine.margin

        init(
            context: UIGraphicsPDFRendererContext,
            bounds: CGRect,
            totalPages: Int,
            footerNote: String = PDFReportEngine.defaultFooterNote
        ) {
            self.context = context
            self.bounds = bounds
            self.totalPages = totalPages
            self.footerNote = footerNote
        }

        func startPage() {
            pageCount += 1
            // The explicit-bounds overload, matching DocumentScannerPDFService's own proven
            // pattern — the bare beginPage() relies on the renderer picking up its format
            // bounds implicitly, which produced an empty (0-byte) PDF.
            context.beginPage(withBounds: bounds, pageInfo: [:])
            y = PDFReportEngine.margin
        }

        /// Draws the footer on the still-open current page, then advances to a new one.
        /// Calling `beginPage()` again implicitly closes whatever page is currently open, so
        /// the footer must be drawn before that call, not after.
        func finishPage() {
            drawFooter()
        }

        private func breakPageIfNeeded(_ needed: CGFloat) {
            guard y + needed > PDFReportEngine.pageHeight - PDFReportEngine.footerHeight else { return }
            finishPage()
            startPage()
        }

        private func drawFooter() {
            let top = PDFReportEngine.pageHeight - PDFReportEngine.footerHeight
            let cg = context.cgContext
            cg.setStrokeColor(Palette.line.cgColor)
            cg.setLineWidth(0.8)
            cg.move(to: CGPoint(x: PDFReportEngine.margin, y: top))
            cg.addLine(to: CGPoint(x: PDFReportEngine.pageWidth - PDFReportEngine.margin, y: top))
            cg.strokePath()

            let noteWidth = PDFReportEngine.pageWidth - PDFReportEngine.margin * 2 - 70
            drawBlock(footerNote, font: Fonts.footer, color: Palette.muted,
                      rect: CGRect(x: PDFReportEngine.margin, y: top + 10, width: noteWidth, height: PDFReportEngine.footerHeight - 14))

            let label = totalPages > 0 ? "Page \(pageCount) of \(totalPages)" : "Page \(pageCount)"
            text(label, topRight: CGPoint(x: PDFReportEngine.pageWidth - PDFReportEngine.margin, y: top + 12), font: Fonts.footer, color: Palette.muted)
        }

        // MARK: Drawing primitives

        func fill(_ rect: CGRect, color: UIColor) {
            color.setFill()
            UIRectFill(rect)
        }

        func round(_ rect: CGRect, radius: CGFloat, color: UIColor) {
            let path = UIBezierPath(roundedRect: rect, cornerRadius: radius)
            color.setFill()
            path.fill()
        }

        func image(_ image: UIImage, rect: CGRect) {
            image.draw(in: rect)
        }

        func text(_ s: String, topLeft: CGPoint, font: UIFont, color: UIColor) {
            (s as NSString).draw(at: topLeft, withAttributes: [.font: font, .foregroundColor: color])
        }

        func text(_ s: String, topRight: CGPoint, font: UIFont, color: UIColor) {
            let width = (s as NSString).size(withAttributes: [.font: font]).width
            text(s, topLeft: CGPoint(x: topRight.x - width, y: topRight.y), font: font, color: color)
        }

        func text(_ s: String, center: CGPoint, font: UIFont, color: UIColor) {
            let size = (s as NSString).size(withAttributes: [.font: font])
            text(s, topLeft: CGPoint(x: center.x - size.width / 2, y: center.y - size.height / 2), font: font, color: color)
        }

        /// Height a wrapped block of [text] would need at [width], without drawing it.
        func measuredHeight(_ text: String, font: UIFont, width: CGFloat) -> CGFloat {
            let bounds = (text as NSString).boundingRect(
                with: CGSize(width: width, height: .greatestFiniteMagnitude),
                options: [.usesLineFragmentOrigin, .usesFontLeading],
                attributes: [.font: font], context: nil
            )
            return ceil(bounds.height)
        }

        func drawBlock(_ text: String, font: UIFont, color: UIColor, rect: CGRect) {
            let paragraph = NSMutableParagraphStyle()
            paragraph.lineBreakMode = .byWordWrapping
            (text as NSString).draw(
                with: rect,
                options: [.usesLineFragmentOrigin, .usesFontLeading],
                attributes: [.font: font, .foregroundColor: color, .paragraphStyle: paragraph],
                context: nil
            )
        }

        // MARK: Layout blocks

        /// Ink header bar with the red accent stripe, logo, right-aligned title/subtitle and timestamp.
        func header(logo: UIImage?, title: String, subtitle: String? = nil) {
            let bandHeight: CGFloat = 104
            fill(CGRect(x: 0, y: 0, width: PDFReportEngine.pageWidth, height: bandHeight), color: Palette.ink)
            fill(CGRect(x: 0, y: bandHeight, width: PDFReportEngine.pageWidth, height: 4), color: Palette.red)

            if let logo {
                let width: CGFloat = 104
                let height = logo.size.height * (width / logo.size.width)
                image(logo, rect: CGRect(x: PDFReportEngine.margin, y: 26, width: width, height: height))
            }

            text(title.uppercased(), topRight: CGPoint(x: PDFReportEngine.pageWidth - PDFReportEngine.margin, y: 22), font: Fonts.title, color: .white)
            var subY: CGFloat = 44
            if let subtitle {
                text(subtitle, topRight: CGPoint(x: PDFReportEngine.pageWidth - PDFReportEngine.margin, y: subY), font: Fonts.sub, color: UIColor(white: 0.65, alpha: 1))
                subY += 14
            }
            text(
                "Generated \(PDFReportEngine.generatedFormatter.string(from: Date()))",
                topRight: CGPoint(x: PDFReportEngine.pageWidth - PDFReportEngine.margin, y: subY),
                font: Fonts.sub, color: UIColor(white: 0.65, alpha: 1)
            )

            y = bandHeight + 4 + 22
        }

        /// Huge document-number identity line, with an optional status pill in caller-supplied
        /// colours — each screen keeps its own established pill styling rather than a shared
        /// pending/active convention that wouldn't match what's actually on screen.
        func identityBlock(
            label: String,
            value: String,
            statusText: String? = nil,
            statusBackground: UIColor = Palette.pendingBg,
            statusForeground: UIColor = Palette.pendingFg
        ) {
            text(label, topLeft: CGPoint(x: PDFReportEngine.margin, y: y), font: Fonts.label, color: Palette.muted)
            y += 14
            text(value, topLeft: CGPoint(x: PDFReportEngine.margin, y: y), font: Fonts.huge, color: Palette.ink)

            if let statusText {
                let statusLabel = statusText.uppercased()
                let textSize = (statusLabel as NSString).size(withAttributes: [.font: Fonts.status])
                let pillWidth = textSize.width + 24
                let pillRect = CGRect(x: PDFReportEngine.pageWidth - PDFReportEngine.margin - pillWidth, y: y - 2, width: pillWidth, height: 20)
                round(pillRect, radius: 9, color: statusBackground)
                text(statusLabel, center: CGPoint(x: pillRect.midX, y: pillRect.midY), font: Fonts.status, color: statusForeground)
            }
            y += 30
        }

        func section(_ title: String) {
            breakPageIfNeeded(46)
            y += 8
            text(title.uppercased(), topLeft: CGPoint(x: PDFReportEngine.margin, y: y), font: Fonts.section, color: Palette.red)
            y += 18
            let cg = context.cgContext
            cg.setStrokeColor(Palette.line.cgColor)
            cg.setLineWidth(0.8)
            cg.move(to: CGPoint(x: PDFReportEngine.margin, y: y))
            cg.addLine(to: CGPoint(x: PDFReportEngine.pageWidth - PDFReportEngine.margin, y: y))
            cg.strokePath()
            y += 14
        }

        /// Two-column label/value grid. Rows whose value is nil are dropped, not rendered blank.
        func grid(_ rows: [(String, String?)]) {
            let present = rows.compactMap { row -> (String, String)? in
                guard let value = row.1 else { return nil }
                return (row.0, value)
            }
            let colWidth = (PDFReportEngine.pageWidth - PDFReportEngine.margin * 2 - PDFReportEngine.colGap) / 2
            var index = 0
            while index < present.count {
                let pair = Array(present[index..<min(index + 2, present.count)])
                let heights = pair.map { measuredHeight($0.1, font: Fonts.value, width: colWidth) }
                let rowHeight = heights.max() ?? 0
                breakPageIfNeeded(rowHeight + 20)
                let rowTop = y
                for (i, (label, value)) in pair.enumerated() {
                    let x = PDFReportEngine.margin + CGFloat(i) * (colWidth + PDFReportEngine.colGap)
                    text(label.uppercased(), topLeft: CGPoint(x: x, y: rowTop), font: Fonts.label, color: Palette.muted)
                    drawBlock(value, font: Fonts.value, color: Palette.ink,
                              rect: CGRect(x: x, y: rowTop + 12, width: colWidth, height: rowHeight + 4))
                }
                y = rowTop + 12 + rowHeight + 12
                index += 2
            }
        }

        /// Full-width label/value, for long text that would be cramped in a grid column.
        func wideRow(label: String, value: String?) {
            guard let value else { return }
            let width = PDFReportEngine.pageWidth - PDFReportEngine.margin * 2
            let height = measuredHeight(value, font: Fonts.value, width: width)
            breakPageIfNeeded(height + 24)
            text(label.uppercased(), topLeft: CGPoint(x: PDFReportEngine.margin, y: y), font: Fonts.label, color: Palette.muted)
            y += 12
            drawBlock(value, font: Fonts.value, color: Palette.ink, rect: CGRect(x: PDFReportEngine.margin, y: y, width: width, height: height + 4))
            y += height + 12
        }

        func paragraph(_ text: String) {
            let width = PDFReportEngine.pageWidth - PDFReportEngine.margin * 2
            let height = measuredHeight(text, font: Fonts.value, width: width)
            breakPageIfNeeded(height + 8)
            drawBlock(text, font: Fonts.value, color: Palette.ink, rect: CGRect(x: PDFReportEngine.margin, y: y, width: width, height: height + 4))
            y += height + 8
        }

        /// Three-column table with a wide first column and two fixed-width columns.
        /// Alternating rows past the first get subtle shading, matching the challan offence
        /// table this was generalised from.
        func table(
            _ rows: [(String, String, String)],
            headers: (String, String, String) = ("OFFENCE", "ACT", "CODE"),
            col2Width: CGFloat = 84,
            col3Width: CGFloat = 64
        ) {
            let col1Width = PDFReportEngine.pageWidth - PDFReportEngine.margin * 2 - col2Width - col3Width - PDFReportEngine.colGap * 2

            breakPageIfNeeded(30)
            text(headers.0, topLeft: CGPoint(x: PDFReportEngine.margin, y: y), font: Fonts.label, color: Palette.muted)
            text(headers.1, topLeft: CGPoint(x: PDFReportEngine.margin + col1Width + PDFReportEngine.colGap, y: y), font: Fonts.label, color: Palette.muted)
            text(headers.2, topLeft: CGPoint(x: PDFReportEngine.margin + col1Width + col2Width + PDFReportEngine.colGap * 2, y: y), font: Fonts.label, color: Palette.muted)
            y += 14
            let cg = context.cgContext
            cg.setStrokeColor(Palette.line.cgColor)
            cg.setLineWidth(0.8)
            cg.move(to: CGPoint(x: PDFReportEngine.margin, y: y))
            cg.addLine(to: CGPoint(x: PDFReportEngine.pageWidth - PDFReportEngine.margin, y: y))
            cg.strokePath()
            y += 10

            for (index, row) in rows.enumerated() {
                let (col1, col2, col3) = row
                let height = measuredHeight(col1, font: Fonts.value, width: col1Width)
                breakPageIfNeeded(height + 16)
                let top = y
                if index % 2 == 1 {
                    round(CGRect(x: PDFReportEngine.margin - 6, y: top - 6, width: PDFReportEngine.pageWidth - PDFReportEngine.margin * 2 + 12, height: height + 16), radius: 6, color: Palette.surface)
                }
                drawBlock(col1, font: Fonts.value, color: Palette.ink, rect: CGRect(x: PDFReportEngine.margin, y: top, width: col1Width, height: height + 4))
                text(col2, topLeft: CGPoint(x: PDFReportEngine.margin + col1Width + PDFReportEngine.colGap, y: top), font: Fonts.value, color: Palette.ink)
                text(col3, topLeft: CGPoint(x: PDFReportEngine.margin + col1Width + col2Width + PDFReportEngine.colGap * 2, y: top), font: Fonts.muted, color: Palette.muted)
                y = top + height + 14
            }
        }
    }
}
