import Foundation

struct CountryInfo: Identifiable, Hashable {
    let id = UUID()
    let name: String
    let isoCode: String
    let phoneCode: String
}

let countries: [CountryInfo] = [
    CountryInfo(name: "Afghanistan", isoCode: "AF", phoneCode: "+93"),
    CountryInfo(name: "Albania", isoCode: "AL", phoneCode: "+355"),
    CountryInfo(name: "Algeria", isoCode: "DZ", phoneCode: "+213"),
    CountryInfo(name: "Argentina", isoCode: "AR", phoneCode: "+54"),
    CountryInfo(name: "Australia", isoCode: "AU", phoneCode: "+61"),
    CountryInfo(name: "Austria", isoCode: "AT", phoneCode: "+43"),
    CountryInfo(name: "Bangladesh", isoCode: "BD", phoneCode: "+880"),
    CountryInfo(name: "Belgium", isoCode: "BE", phoneCode: "+32"),
    CountryInfo(name: "Brazil", isoCode: "BR", phoneCode: "+55"),
    CountryInfo(name: "Canada", isoCode: "CA", phoneCode: "+1"),
    CountryInfo(name: "China", isoCode: "CN", phoneCode: "+86"),
    CountryInfo(name: "Egypt", isoCode: "EG", phoneCode: "+20"),
    CountryInfo(name: "Ethiopia", isoCode: "ET", phoneCode: "+251"),
    CountryInfo(name: "France", isoCode: "FR", phoneCode: "+33"),
    CountryInfo(name: "Germany", isoCode: "DE", phoneCode: "+49"),
    CountryInfo(name: "Ghana", isoCode: "GH", phoneCode: "+233"),
    CountryInfo(name: "Greece", isoCode: "GR", phoneCode: "+30"),
    CountryInfo(name: "India", isoCode: "IN", phoneCode: "+91"),
    CountryInfo(name: "Indonesia", isoCode: "ID", phoneCode: "+62"),
    CountryInfo(name: "Iran", isoCode: "IR", phoneCode: "+98"),
    CountryInfo(name: "Iraq", isoCode: "IQ", phoneCode: "+964"),
    CountryInfo(name: "Ireland", isoCode: "IE", phoneCode: "+353"),
    CountryInfo(name: "Israel", isoCode: "IL", phoneCode: "+972"),
    CountryInfo(name: "Italy", isoCode: "IT", phoneCode: "+39"),
    CountryInfo(name: "Jamaica", isoCode: "JM", phoneCode: "+1"),
    CountryInfo(name: "Japan", isoCode: "JP", phoneCode: "+81"),
    CountryInfo(name: "Jordan", isoCode: "JO", phoneCode: "+962"),
    CountryInfo(name: "Kenya", isoCode: "KE", phoneCode: "+254"),
    CountryInfo(name: "Kuwait", isoCode: "KW", phoneCode: "+965"),
    CountryInfo(name: "Malaysia", isoCode: "MY", phoneCode: "+60"),
    CountryInfo(name: "Mexico", isoCode: "MX", phoneCode: "+52"),
    CountryInfo(name: "Morocco", isoCode: "MA", phoneCode: "+212"),
    CountryInfo(name: "Nepal", isoCode: "NP", phoneCode: "+977"),
    CountryInfo(name: "Netherlands", isoCode: "NL", phoneCode: "+31"),
    CountryInfo(name: "New Zealand", isoCode: "NZ", phoneCode: "+64"),
    CountryInfo(name: "Nigeria", isoCode: "NG", phoneCode: "+234"),
    CountryInfo(name: "Norway", isoCode: "NO", phoneCode: "+47"),
    CountryInfo(name: "Oman", isoCode: "OM", phoneCode: "+968"),
    CountryInfo(name: "Pakistan", isoCode: "PK", phoneCode: "+92"),
    CountryInfo(name: "Philippines", isoCode: "PH", phoneCode: "+63"),
    CountryInfo(name: "Poland", isoCode: "PL", phoneCode: "+48"),
    CountryInfo(name: "Portugal", isoCode: "PT", phoneCode: "+351"),
    CountryInfo(name: "Qatar", isoCode: "QA", phoneCode: "+974"),
    CountryInfo(name: "Russia", isoCode: "RU", phoneCode: "+7"),
    CountryInfo(name: "Saudi Arabia", isoCode: "SA", phoneCode: "+966"),
    CountryInfo(name: "Singapore", isoCode: "SG", phoneCode: "+65"),
    CountryInfo(name: "South Africa", isoCode: "ZA", phoneCode: "+27"),
    CountryInfo(name: "South Korea", isoCode: "KR", phoneCode: "+82"),
    CountryInfo(name: "Spain", isoCode: "ES", phoneCode: "+34"),
    CountryInfo(name: "Sri Lanka", isoCode: "LK", phoneCode: "+94"),
    CountryInfo(name: "Sweden", isoCode: "SE", phoneCode: "+46"),
    CountryInfo(name: "Switzerland", isoCode: "CH", phoneCode: "+41"),
    CountryInfo(name: "Thailand", isoCode: "TH", phoneCode: "+66"),
    CountryInfo(name: "Turkey", isoCode: "TR", phoneCode: "+90"),
    CountryInfo(name: "Ukraine", isoCode: "UA", phoneCode: "+380"),
    CountryInfo(name: "United Arab Emirates", isoCode: "AE", phoneCode: "+971"),
    CountryInfo(name: "United Kingdom", isoCode: "GB", phoneCode: "+44"),
    CountryInfo(name: "United States", isoCode: "US", phoneCode: "+1"),
    CountryInfo(name: "Vietnam", isoCode: "VN", phoneCode: "+84")
]
